### ISSUE TITLE
converter for fragpipe output to MSstatsPTM

### ISSUE THREAD

**Issue by mt-forrester** [Vitek-Lab/MSstatsPTM#45]
Hello. I'm studying protein S-acylation and would very much like to use the MSstatsPTM package on our TMT dataset. However our fragpipe output would require a fair amount preprocessing to be compatible with MSstatsPTM. I'm in the process of trying to write a converter but wondering if you folks already have tackled this problem and would be able to share or guide me? Thanks so much in advance.

**Comment by patmartinezb** [comment]
In line with this, converter o any help with DDA LFQ FragPipe output would also be greatly appreciated! Thank you!

**Comment by devonjkohler** [comment]
Hey @mt-forrester,

I am adding a Fragpipe converter today as a bug fix (`PhilosophertoMSstatsPTM`). It should be available in Bioc tomorrow, and is available in Github now. It requires a new version of Philosopher to output the correct files, so you need to make sure to update on their side as well. 

@patmartinezb I am currently working with Fragpipe for LFQ. They have a file output on their side to automatically put LFQ data into MSstats format which will work for non-PTM data. Hopefully will have a solution for PTM data soon.

**Comment by reynoldsanthony** [comment]
Hello, I wanted to follow up on this thread as I am also encountering an issue when trying to use MSstats to analyze PTM MS data from FragPipe, has there been any update to this issue? I'm unable to access the Philosopher fix mentioned by Devon above. Thanks!

**Comment by devonjkohler** [comment]
Hi @reynoldsanthony,

What error are you encountering when using the converter? We updated the FragPipe converter for TMT output a couple months ago, so the older errors for this issue should be fixed.

Devon

**Comment by reynoldsanthony** [comment]
Hi Devon, 

Thank you so much for reaching out!

I am trying to convert a FragPipe generated, modified-peptide document from a label free DDA dataset. I'm unable to get the data converted into the MSstatsPTM nomenclature ie. Gene Name_Modification Site
Is there FragPipe specific converter I can use or recommendations for me to get around this obstacle?

Thank you again, 
Anthony Reynolds

**Comment by devonjkohler** [comment]
Quick update on this converter.

We are working directly with FragPipe to output their label free PTM data into the msstats.csv file. Currently only TMT PTM data is supported but this should be corrected shortly.

**Comment by devonjkohler** [comment]
Label free functionality has been added to the converter. FrapPipe will now add PTM info into the LF msstats.csv file. This requires the newest version of FragPipe in order to work correctly.

The new converter is currently available on Github and will be added to Bioc shortly.

**Comment by direnardak** [comment]
Hello, I have DDA phosphoproteomics data but I am still not able to use the output from FragPipe to run MSstatsPTM. I am using FragPipe v20.0 and MSstatsPTM v2.5.1. Are the versions correct?
